#!/bin/bash
#PBS -N HCHRecSFICTMP
#PBS -q standard
#PBS -r n
#PBS -l walltime=0:5:0
#PBS -o output/OUT_HC${VAR2}_gaps-${VAR3}_G-${VAR4}_B-${VAR7}_P-${VAR5}_T-${VAR9}_pDD-${VAR10}_iPP-${VAR11}_${PBS_JOBID}.txt
#PBS -e output/ERR_HC${VAR2}_gaps-${VAR3}_G-${VAR4}_B-${VAR7}_P-${VAR5}_T-${VAR9}_pDD-${VAR10}_iPP-${VAR11}_${PBS_JOBID}.txt

#UWAGA #1 !!! Pamietac o tym, ze plik konfiguracji LOAD bedzie zawieral wartosc argumentu do 8 miejsc po przecinku, zaokraglana do 3 w nazwie. Jezeli tworzona jest konfiguracja poczatkowa 'ze srodka zakresu symulacji' (przy dzieleniu calosci na kilka niezaleznych czesci), nalezy zadac jej odpowiednia dokladnosc (im wieksza tym lepiej), aby zle zaokraglenia nie wplynely na 3 pierwsze cyfry znaczace nazw (takie punkty sie wysypia, bo obliczenia na podstawie 'pointNumber' beda lecialy z dokladnoscia typu double od startArg -> i odpowiednie pliki moga nie zostac znalezione).

#UWAGA #2 !!! Pamietac o wyzerowaniu liczby krokow generatora liczb pseudolosowych (by niepotrzebnie nie czekac na to przy pierwszym runie -> OPCJA W CONFIGU) oraz o ustawieniu configu na startowanie generatora z zegara CPU.

#$VAR1-job_id jobu, ktory zawieral loadowany punkt, $VAR2-N, $VAR3-gaps, $VAR4-growing, $VAR5-pointNumber(from 0), $VAR6-iterationsNumber, $VAR7-useSpecificDirectory (UWAGA: NIE 0), $VAR8-MAX(+1)PointNumber(from 0), $filterText-filterText, $VAR9-T, $VAR10-polydisperseDelta, $VAR11-invPotPower


cd $PBS_O_WORKDIR
#pressure do 3 miejsc po przecinku (zeby pasowalo do nazw plikow, lista DOMYSLNIE na G=1)
listLength=$(wc -l startArguments.txt | cut -f1 -d' ');
if [ ${VAR4} = 1 ]; then
   PRESSURE=$(cut -f2 startArguments.txt | head -n $((${VAR5} + 1)) | tail -1);
else
   PRESSURE=$(cut -f2 startArguments.txt | head -n $((${listLength} - ${VAR5})) | tail -1);
fi

#UWAGA #3: PBS tworzy indywidualny folder tmp dla kazdego zadania
cd $TMPDIR
pwd
echo "==============================="

cp $PBS_O_WORKDIR/program .
cp $PBS_O_WORKDIR/config.txt .
cp $PBS_O_WORKDIR/startArguments.txt .
echo "files copied"
mkdir 3D_N-${VAR2}_gaps-${VAR3}_G-${VAR4}_badanie-${VAR7}_T-${VAR9}_pDD-${VAR10}_iPP-${VAR11}
cp $PBS_O_WORKDIR/3D_N-${VAR2}_gaps-${VAR3}_G-${VAR4}_badanie-${VAR7}_T-${VAR9}_pDD-${VAR10}_iPP-${VAR11}/j-${VAR1}_Configurations_arg-${PRESSURE}.txt 3D_N-${VAR2}_gaps-${VAR3}_G-${VAR4}_badanie-${VAR7}_T-${VAR9}_pDD-${VAR10}_iPP-${VAR11} && {

   #UWAGA #4: Mozna do programu zadac jobID rowny np. 'repeats left' (lub 'none' gdy to zwykla rekurencja [a nie onePoint]). Wtedy w przypadku ewentualnej reanimacji powinno byc latwiej (bo: komenda 'sacct' [i podobne], czy nawet zapis w ERR [jezeli akurat powstanie - na co liczyc nie mozna] da co prawda informacje o jobID nieudanego jobu, jednak NIE DA informacji o jobID jobu 'poprzedniego' [z ktorego on korzystal i ktorego znajomosc potrzebna jest do reanimacji]) - nie bedzie trzeba go szukac po folderach indywidualnie dla kazdego reanimowanego jobu.
   time ./program 4 $VAR1 $VAR1 $VAR2 $VAR3 $VAR4 $VAR5 $VAR6 $VAR7 0 ${VAR9} ${VAR10} ${VAR11}

   cp -fr 3D_N-${VAR2}_gaps-${VAR3}_G-${VAR4}_badanie-${VAR7}_T-${VAR9}_pDD-${VAR10}_iPP-${VAR11} $PBS_O_WORKDIR
   #UWAGA #5: PBS kasuje po sobie tempa automatycznie

   ssh ce.reef.man.poznan.pl "cd $PBS_O_WORKDIR; qsub -N ${filterText}G${VAR4}B${VAR7}P$(($VAR5 + $VAR6)) -o output/OUT_HC${VAR2}_gaps-${VAR3}_G-${VAR4}_B-${VAR7}_P-$(($VAR5 + $VAR6))_T-${VAR9}_pDD-${VAR10}_iPP-${VAR11}_prevJobID-${PBS_JOBID}.txt -e output/ERR_HC${VAR2}_gaps-${VAR3}_G-${VAR4}_B-${VAR7}_P-$(($VAR5 + $VAR6))_T-${VAR9}_pDD-${VAR10}_iPP-${VAR11}_prevJobID-${PBS_JOBID}.txt -v VAR1=$VAR1,VAR2=$VAR2,VAR3=$VAR3,VAR4=$VAR4,VAR5=$(($VAR5 + $VAR6 - 1)),VAR6=$VAR6,VAR7=$VAR7,VAR8=$VAR8,filterText=${filterText},VAR9=${VAR9},VAR10=${VAR10},VAR11=${VAR11} qsubTMPRecursion";
   #ui.inula.man.poznan.pl
} || {
   echo "Missing configuration file (previous job failed) or actual job failed at any step. Stopping recursion.";
}

exit 0
