#!/bin/bash
#PBS -N HCHRecTMP
#PBS -q standard
#PBS -r n
#PBS -l walltime=0:5:0
#standardowy output i error zlecane z poziomu wywołania qsuba - bo tutaj nie działają operacje typu $(())

#$VAR1-job_id jobu, ktory zawieral loadowany punkt, $VAR2-N, $VAR3-gaps, $VAR4-multimerS, $VAR5-multimerD, $VAR6-growing, $VAR7-pointNumber(from 0), $VAR8-iterationsNumber, $VAR9-useSpecificDirectory (UWAGA: NIE 0), $VAR10-MAX(+1)PointNumber(from 0), $filterText-filterText, $VAR11-multimerN

cd $PBS_O_WORKDIR
#pressure do 3 miejsc po przecinku (zeby pasowalo do nazw plikow, lista DOMYSLNIE na G=1)
listLength=$(wc -l startArguments.txt | cut -f1 -d' ');
if [ ${VAR6} = 1 ]; then
   PRESSURE=$(cut -f2 startArguments.txt | head -n $((${VAR7} + 1)) | tail -1);
else
   PRESSURE=$(cut -f2 startArguments.txt | head -n $((${listLength} - ${VAR7})) | tail -1);
fi

#UWAGA #1: PBS tworzy indywidualny folder tmp dla kazdego zadania
cd $TMPDIR
pwd
echo "==============================="

cp $PBS_O_WORKDIR/program .
cp $PBS_O_WORKDIR/config.txt .
cp $PBS_O_WORKDIR/startArguments.txt .
mkdir 2D_N-${VAR2}_gaps-${VAR3}_G-${VAR6}_badanie-${VAR9}_mN-${VAR11}_mS-${VAR4}_mD-${VAR5}
cp $PBS_O_WORKDIR/2D_N-${VAR2}_gaps-${VAR3}_G-${VAR6}_badanie-${VAR9}_mN-${VAR11}_mS-${VAR4}_mD-${VAR5}/j-${VAR1}_Configurations_arg-${PRESSURE}.txt 2D_N-${VAR2}_gaps-${VAR3}_G-${VAR6}_badanie-${VAR9}_mN-${VAR11}_mS-${VAR4}_mD-${VAR5} && {

   #UWAGA #2: Mozna do programu zadac jobID rowny np. 'repeats left' (lub 'none' gdy to zwykla rekurencja [a nie onePoint]). Wtedy w przypadku ewentualnej reanimacji powinno byc latwiej (bo: komenda 'sacct' [i podobne], czy nawet zapis w ERR [jezeli akurat powstanie - na co liczyc nie mozna] da co prawda informacje o jobID nieudanego jobu, jednak NIE DA informacji o jobID jobu 'poprzedniego' [z ktorego on korzystal i ktorego znajomosc potrzebna jest do reanimacji]) - nie bedzie trzeba go szukac po folderach indywidualnie dla kazdego reanimowanego jobu.
   time ./program 4 $VAR1 $VAR1 $VAR2 $VAR3 $VAR4 $VAR5 $VAR6 $VAR7 $(($VAR8 + 1)) $VAR9 1 ${VAR11}

   cp -fr 2D_N-${VAR2}_gaps-${VAR3}_G-${VAR6}_badanie-${VAR9}_mN-${VAR11}_mS-${VAR4}_mD-${VAR5} $PBS_O_WORKDIR
   #UWAGA #3: PBS kasuje po sobie tempa automatycznie

   if [ $(($VAR7 + $VAR8 + 1)) -lt $VAR10 ]; then 
   ssh ce.reef.man.poznan.pl "cd $PBS_O_WORKDIR; qsub -N ${filterText}G${VAR6}B${VAR9}P$(($VAR7 + $VAR8 + 1)) -o output/OUT_HC${VAR11}_${VAR2}_gaps-${VAR3}_mS-${VAR4}_mD-${VAR5}_G-${VAR6}_B-${VAR9}_P-$(($VAR7 + $VAR8 + 1))_prevJobID-${PBS_JOBID}.txt -e output/ERR_HC${VAR11}_${VAR2}_gaps-${VAR3}_mS-${VAR4}_mD-${VAR5}_G-${VAR6}_B-${VAR9}_P-$(($VAR7 + $VAR8 + 1))_prevJobID-${PBS_JOBID}.txt -v VAR1=$VAR1,VAR2=$VAR2,VAR3=$VAR3,VAR4=$VAR4,VAR5=$VAR5,VAR6=$VAR6,VAR7=$(($VAR7 + $VAR8)),VAR8=$VAR8,VAR9=$VAR9,VAR10=$VAR10,filterText=${filterText},VAR11=${VAR11} qsubTMPRecursion";
   #ui.inula.man.poznan.pl
   fi
} || {
   echo "Missing configuration file (previous job failed) or actual job failed at any step. Stopping recursion.";
}

exit 0
